#Local MongoDB config
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: biblihoteque
  # SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

